version: "3"
services:
  app:
    image: busybox
    volumes:
      - ../:/var/www/html/template.com
      - ./var/log:/var/log
    tty: true
  php:
    build: ./php
    env_file: ../environment/development/.env
    links:
      - mysql
    volumes_from:
      - app
  nginx:
    build: ./nginx
    ports: 
      - 13000:80
    links:
      - php
    volumes_from:
      - app
  mysql:
    build: ./mysql
    env_file: ../environment/development/.env
    ports:
      - 13001:3306
    user: 1000:1000
    environment:
      - "TZ=Asia/Tokyo"
    volumes:
      - ../.mysql:/var/lib/mysql
    volumes_from:
      - app